## IR codes
SPLITTER_AUDIO_CAST: str = 'B+cjexGwAscB4BUDATgG4CED4CtLByyc5yOkCLAC'
SPLITTER_TV: str = 'BbMjrxFAAuAXAQGjBuAZA8ABwCvgBwHgBxfAD0AHD3+csyO2CIAC//+zI7YIQAI='
VOLUME_UP: str = "BlQjzBEWAl4gAQHABkAHgAPgAwvgAxPAF0AHQANAAeADH0AL4AEXQAEBFgJAA0AT4AcHC8AGFgLABhYCwAYWAg=="
VOLUME_DOWN: str = "DbMjexF/AvcBfwJTBn8CQAdAA+ADC0APQANAE0AD4AcL4AcPwCNAF+AHA8AbQAfgAwMPDKWzI5IIfwL//7Mjkgh/Ag=="

IR_TEXT_ENTITY: str = "text.ab35847d2a960e673d91dc3955ea60ef"