name: Release Home Assistant Pyscript

on:
  push:
    branches: [ never ]   # releasing is no really needed

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zip the pyscript folder
        run: |
          zip -r pyscript.zip pyscript/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1 
        with:
           tag_name: release-${{ github.run_number }}
           name: "HA Pyscript ${{ github.run_number }}"
           body: "Auto-release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          files: pyscript.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
